name: "workflow command"

on:
  push:
    branches:
        - main

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
        - name: group log
          run: |
            echo "::group::my group messages"
            echo "msg1"
            echo "msg2"
            echo "::endgroup::"
        - name: step 1
          run: |
            echo "MY_VAL=hello" >> $GITHUB_ENV
        - name: step 1
          run: |
            echo $MY_VAL
