name: conditional
on:
    push:
      branches:
        - main
jobs:
    greeting:
        if: github.repository == 'hellowrold/Github-Examples'
        runs-on: ubuntu-latest
        steps:
            - name: greet the owner
              run: echo "hello world"

    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: sayonara
              run: echo "goodbye"