name: testing expressions

on:
  push:
    branches:
      - main
  issues:
    types: [opened, labeled]
jobs:
    expressions:
      runs-on: ubuntu-latest
      steps:
        - name: starts with he
          if: contains('hello world', 'he')
          run: echo "the shit contains he"
        - name: check if string starts with
          if: startsWith('asdfasdf', 'as')
          run: echo "the string starts with as"
        - name: check if the string endswith
          if: endsWith('asdf', 'f')
          run: echo "the string ends with"
        - name: echo string
          run: echo "hello hhh asdf"
        - name: join issue labels
          if: github.event_name == 'issues'
          run: echo 'issue labels ${{join(github.event.issue.labels.*.name,', ')}}'
        - name: Convert job context to JSON
          run: echo "Job context in JSON: ${{ toJSON(github.job) }}"
        - name: Parse JSON string
          run: echo "Parsed JSON: ${{ fromJSON('{"hello":"world"}').hello }}"
        - name: Hash files
          run: echo "Hash of files: ${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}"
        - name: The job has succeeded
          if: success()
        - name: The job has failed
          if: failure()