name: Print GitHub Context Info

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo basic info"
        run: |
          echo "REF: $GITHUB_REF"
          echo "JOB: $GITHUB_JOB"
          echo "WORKFLOW: $GITHUB_WORKFLOW"
          echo "ACTOR: $GITHUB_ACTOR"
          echo "RUNNING IN ACTIONS? $GITHUB_ACTIONS"